apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80
  selector:
    app.kubernetes.io/name: nginx