name: 'Terraform GitHub Actions'
on:
  - pull_request
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: hashicorp/terraform-github-actions@master
      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'fmt'
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.subscription_id }}
          ARM_TENANT_ID: ${{ secrets.tenant_id }}
          ARM_CLIENT_ID: ${{ secrets.client_id }}
          ARM_CLIENT_SECRET: ${{ secrets.client_secret }}
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'init'
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.subscription_id }}
          ARM_TENANT_ID: ${{ secrets.tenant_id }}
          ARM_CLIENT_ID: ${{ secrets.client_id }}
          ARM_CLIENT_SECRET: ${{ secrets.client_secret }}
      - name: 'Terraform Validate'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'validate'
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.subscription_id }}
          ARM_TENANT_ID: ${{ secrets.tenant_id }}
          ARM_CLIENT_ID: ${{ secrets.client_id }}
          ARM_CLIENT_SECRET: ${{ secrets.client_secret }}
      - name: 'Terraform Plan'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'plan'
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.subscription_id }}
          ARM_TENANT_ID: ${{ secrets.tenant_id }}
          ARM_CLIENT_ID: ${{ secrets.client_id }}
          ARM_CLIENT_SECRET: ${{ secrets.client_secret }}