name: 'Terraform GitHub Actions'
on:
  - pull_request
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: evry-ace/devops-training-omega@development
      - name: 'Terraform Format'
        uses: evry-ace/devops-training-omega@development
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'fmt'
        env:
          GITHUB_TOKEN: ${{ secrets.subscription_id }}
          GITHUB_TOKEN: ${{ secrets.tenant_id }}
      - name: 'Terraform Init'
        uses: evry-ace/devops-training-omega@development
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'init'
        env:
          GITHUB_TOKEN: ${{ secrets.subscription_id }}
          GITHUB_TOKEN: ${{ secrets.tenant_id }}
      - name: 'Terraform Validate'
        uses: evry-ace/devops-training-omega@development
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'validate'
        env:
          GITHUB_TOKEN: ${{ secrets.subscription_id }}
          GITHUB_TOKEN: ${{ secrets.tenant_id }}
      - name: 'Terraform Plan'
        uses: evry-ace/devops-training-omega@development
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'plan'
        env:
          GITHUB_TOKEN: ${{ secrets.subscription_id }}
          GITHUB_TOKEN: ${{ secrets.tenant_id }}
      - name: 'Terraform Apply'
        uses: evry-ace/devops-training-omega@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'apply -auto-approve'
        env:
          GITHUB_TOKEN: ${{ secrets.subscription_id }}
          GITHUB_TOKEN: ${{ secrets.tenant_id }}